---
- hosts: servers
  roles:
    - common
    - provision
    - s3_cmd
    - harden
    - users
    # - { role: backup_ynr, when: "deploy_env == 'production'" }
    # - { role: restore_from_ynr_backup, when: "deploy_env == 'staging'" }
  vars_files:
    - vars.yml
    - vault.yml
  gather_facts: true
  become: true
- import_playbook: deploy.yml
