---
# Backups
- name: install s3cmd
  apt:
    pkg: s3cmd
    state: installed
  tags: package

- name: Install DB backup script.
  template:
    src: "files/scripts/backup.sh dest={{ project_root }}/backup.sh"
    mode: "u+rwx"
    owner: "{{project_name}}"

- name: Install images backup script.
  template:
    src: "files/scripts/backup_images.sh"
    dest: "{{ project_root }}/backup_images.sh"
    mode: "u+rwx"
    owner: "{{project_name}}"

- name: configure s3cmd
  sudo: true
  template: >
    src=files/conf/s3cmd.conf
    dest={{project_root}}/home/.s3cfg


- name: Set up the mailto
  cronvar:
    name: "MAILTO"
    value: "developers@democracyclub.org.uk"
    user: "{{project_name}}"

- name: Set up the DB backup cron
  cron:
    name: "backup {{project_name}}"
    minute: "30"
    job: "{{ project_root }}/backup.sh > /dev/null"
    user: "{{project_name}}"

- name: Set up the images backup cron
  cron:
    name: "backup {{project_name}} images"
    minute: "40"
    job: "{{ project_root }}/backup_images.sh > /dev/null"
    user: "{{project_name}}"
