---
- name: Create user.
  user:
    name: celery
    home: /opt/celery/
    state: present

- name: Create directories for celery
  file: name={{ item }} state=directory owner={{ project_name }}
  with_items:
    - /etc/conf.d/
    - /var/run/celery/
    - /var/log/celery/

- name: Set up the celery config file
  template:
    src: celery.conf
    dest: /etc/conf.d/celery
  when: ansible_distribution_version == "16.04"
  notify:
    - reload systemd
    - restart celery

- name: Install celery systemd init scripts.
  template:
    src: celery.service
    dest: /etc/systemd/system/celery.service
  when: ansible_distribution_version == "16.04"
  notify:
    - reload systemd
    - restart celery
