---
- name: Clone Certbot into configured directory.
  git:
    repo: https://github.com/certbot/certbot.git
    dest: /opt/certbot
    version: master
    update: yes
    force: yes

- name: Set Certbot script variable.
  set_fact:
    certbot_script: "/opt/certbot/certbot-auto"

- name: Ensure certbot-auto is executable.
  file:
    path: "{{ certbot_script }}"
    mode: 0755
