---
- name: restart nginx
  service: name=nginx state=restarted
  become: true

- name: reload nginx
  service: name=nginx state=reloaded
  become: true

- name: restart web frontend
  action: service name={{ project_name }}_gunicorn state=restarted
  become: true
  become_user: root

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: restart rsyslog
  service: name=rsyslog state=restarted
  become: True
  become_user: root
