---
# Restore from backup
- name: install s3cmd
  apt:
    pkg: s3cmd
    state: installed
  tags: package

- name: Install DB backup restore script.
  template:
    src: files/scripts/restore_from_backup.sh
    dest: "{{ project_root }}/restore_from_backup.sh"
    mode: "u+rwx"
    owner: "{{project_name}}"

- name: configure s3cmd
  template:
    src: files/conf/s3cmd.conf
    dest: "{{project_root}}/home/.s3cfg"
  become_user: "{{project_name}}"
  become: true

- name: Set up the mailto
  cronvar:
    name: "MAILTO"
    value: "developers@democracyclub.org.uk"
    user: "{{project_name}}"

- name: Set up the DB backup cron
  cron:
    name: "backup {{project_name}}"
    minute: "30"
    hour: 4
    job: "{{ project_root }}/restore_from_backup.sh > /dev/null"
    user: "{{project_name}}"

- name: Restore latest database
  shell: |
    ./restore_from_backup.sh
  args:
    chdir: "{{ project_root }}"
    executable: /bin/bash
  become_user: "{{project_name}}"
  become: true
  when: restore_on_deploy is defined
